# This is a basic workflow to help you get started with Actions

name: BuildHtml5

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4
      # Runs a set of commands using the runners shell
      - name: wow its building how
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib haxe -y
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install hxcpp
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-ui
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install hscript
          haxelib install newgrounds
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list
          haxelib run lime build html5
      - name: Get malded nerd
        run: |
          echo cry bitch
          echo get nerd'd
          echo lmao
          echo malder lmao
          echo lmaoooooooooooooooo
          echo fat L
          echo fat LLLLLLLLLLLL
          echo mald you cry baby
          echo mald goes home
          echo lmaoooooooooooooooooooooooooooooooooooooooooooooo
          echo malding fr rn
          echo you crazy?
          echo maldin ass mf
          echo lmaoooooooooooooo
          echo look what the bitch detector picked up
          echo fuckin crybaby bitch
          echo Ok, I'm sorry, I just wanted to run this in a workflow lmao.
      - uses: actions/upload-artifact@v2
        with:
          name: htmlBuild
          path: export/release/html5/bin

