# This is a basic workflow to help you get started with Actions

name: BuildWin

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-ui
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib install hscript
          haxelib install newgrounds
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list
      - name: Get malded nerd
        run: |
          echo cry bitch
          echo get nerd'd
          echo lmao
          echo malder lmao
          echo lmaoooooooooooooooo
          echo fat L
          echo fat LLLLLLLLLLLL
          echo mald you cry baby
          echo mald goes home
          echo lmaoooooooooooooooooooooooooooooooooooooooooooooo
          echo malding fr rn
          echo you crazy?
          echo maldin ass mf
          echo lmaoooooooooooooo
          echo look what the bitch detector picked up
          echo fuckin crybaby bitch
          echo Ok, I'm sorry, I just wanted to run this in a workflow lmao.
        shell: cmd
      - name: Create APIStuff
        run: echo "package;class APIStuff{public static var API:String = '';public static var EncKey:String = '';}" > source/APIStuff.hx
      - name: Compile
        run: haxelib run lime build windows
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windowsBuild
          path: export/release/windows/bin
